"""adiciona coluna 'publicado em' na tabela de posts

Revision ID: 22cd4abf332b
Revises: 95cee9bb983e
Create Date: 2025-12-25 17:01:01.106628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cd4abf332b'
down_revision = '95cee9bb983e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('published_at')

    # ### end Alembic commands ###
