"""adiciona campo que indica se é draft

Revision ID: 931751b72399
Revises: 3c17615241b8
Create Date: 2025-10-28 20:02:14.230292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931751b72399'
down_revision = '3c17615241b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=False, server_default='1'))

    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.drop_column('is_draft')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_column('is_draft')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('is_draft')

    # ### end Alembic commands ###
