"""ajusta lógica dos drafts

Revision ID: 95cee9bb983e
Revises: 931751b72399
Create Date: 2025-10-28 20:33:14.239036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95cee9bb983e'
down_revision = '931751b72399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_column('is_draft')

    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.drop_column('is_draft')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False))

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False))

    # ### end Alembic commands ###
