"""adiciona dimensoes para as imagens

Revision ID: d4a6dfc7b9ad
Revises: 22cd4abf332b
Create Date: 2026-07-29 19:51:52.891027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a6dfc7b9ad'
down_revision = '22cd4abf332b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fileWidth', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fileHeight', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.drop_column('fileHeight')
        batch_op.drop_column('fileWidth')

    # ### end Alembic commands ###
